### ISSUE TITLE
Unable to run core-scaling-ui on a separate server

### ISSUE THREAD

**Issue by newmans99** [qlik-oss/core-scaling-ui#148]
When trying to get the sample to run in a headless environment I am getting the following error:
"WebSocket network error: The operation couldn’t be completed. Connection refused" in my browser (on a separate machine).

I have modified the standard package.json file to start the dev webserver as:
webpack-dev-server --mode development --hot --host IP_ADDRESS

where IP_ADDRESS is my IP address or I have even tried 0.0.0.0.

Any other thoughts or ideas on how to get this to run?

**Comment by hrigner** [comment]
The issue was resolved by setting the engine URL in the enigma.config file.
