### ISSUE TITLE
Core Scaling UI not running into a server running Linux

### ISSUE THREAD

**Issue by cleveranjos** [qlik-oss/core-scaling-ui#160]
I´ve created a linux box for Qlik Core demo
Steps I´ve done

1. Provisioned a Linux box into AWS and created a security group opening all TCP ports to outside world
2. Installed and checked Docker
3. Steps
git clone https://github.com/qlik-oss/core-scaling-ui.git
cd core-scaling-ui/
ACCEPT_EULA=yes docker-compose up -d
npm install
npm run start

if I try to connect to localhost (into my Linux box) with curl for example everything is fine
$ curl localhost:8080
<!DOCTYPE html>
<html lang="en">
<head>
 ...
</html>

but if I try to point a browser to that public IP box using a browser it does not answer

**Comment by hrigner** [comment]
When running npm run start you run the UI in development mode, which means that the engine is supposed to be found on localhost:9176 (just FYI, the other supported mode is production where the engine in running in Kubernetes environment).

So, we are looking for an engine on localhost:9176 (see enigma.config and docker-compose file). When connecting from your browser, localhost will be the localhost where the browser is running (probably not the Linux box?). If you want to connect to the engine on another IP (the Linux box IP), you can manually change this the in enigma.config file.

Try this, and let me know the progress! :)

**Comment by hrigner** [comment]
If your Qlik Associative Engine image is accessible on core.mydocker.online:9176, then yes. So, does the change make any difference? :)

Can you see the web page at all at yourhost:8080? If yes, can you connect to the Engine, or do you get connection error? Can you check the browser developer tools -> network tab and see what's being sent and received on the websocket?

**Comment by cleveranjos** [comment]
Helene, I found the problem. It´s a network problem, not related to the
container itself

----------------------------
Cléver Anjos
clever@clever.com.br
להעביר אותנו מן הרע
"it is impossible to sharpen a pencil with a blunt axe. It is equally vain
to try to do it with ten blunt axes instead." Edsger W.Dijkstra

**Comment by hrigner** [comment]
So, I have it running on an aws ec2 instance. My changes needed:

- In webpack.config.js, add `devServer: { host: '0.0.0.0', port: '8080', disableHostCheck: true }`.
- In enigma.config.js line 3, change localhost to the IP of the ec2 instance, `const backendAdress = process.env.NODE_ENV === 'production' ? `${process.env.BACKEND}/app/doc/5f5f03fe-00f3-4a4b-ac52-db32152a7e44` : 'XX.XXX.XX.XX:9176';`
- Open webpack port (8080) and the port used in the container running the QIX Engine (9176).

**Comment by cleveranjos** [comment]
Worked like a charm!
