### ISSUE TITLE
Core Scaling UI app is not running. It throws app not found

### ISSUE THREAD

**Issue by rajasekar-d** [qlik-oss/core-scaling-ui#64]
### Description

Core Scaling UI app is not running. It throws app not found

### Steps to Reproduce

1. ACCEPT_EULA=yes docker-compose up -d
2. npm install
3. npm run start

##### Expected behavior

It should read qvf and create container image, also render a charts

##### Actual behavior

Core Scaling UI app is not running. It throws app not found.

##### Library
```
* Node.js 
* Browser
* Docker Community edition
```
##### Operating system
```
* Windows 10
```
##### Versions
```
* Node.js: v9.10.1
* Browser: 62.0.3202.62 (Official Build) (64-bit)
* Docker Community edition: 18.03.0-ce-win59 (16762)
```

**Comment by carlioth** [comment]
Hello, thank you for your issue. 
I can think of two things that might be causing this. 

1. Shared drive issue: Please go to settings for Docker and do a "reset credentials" and then share your drive again. After that please try to do the steps to reproduce again. 

2. Port collision. If you are running Qlik Sense Desktop on the same machine, you will have an issue with a collision of port 9076. Try closing your Sense Desktop and then do the steps to reproduce again.

Hope this will resolve your issues.

**Comment by rajasekar-d** [comment]
Thanks @carlioth 
After resetting credentials, Now it's working fine.
